package com.example.bookservice.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.example.bookservice.common.Common;
import com.example.bookservice.dtos.CreateBookDTO;
import lombok.Data;

@DynamoDBTable(tableName = Common.BOOK_TABLE)
@Data
public class Book {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String uuid;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String isbn;
    @DynamoDBAttribute
    private String authorUuid;

    public static Book createBook(CreateBookDTO dto){
        Book newBook = new Book();
        newBook.setIsbn(dto.getIsbn());
        newBook.setTitle(dto.getTitle());
        newBook.setAuthorUuid(dto.getAuthorUuid());
        return newBook;
    }
}
