server:
  port: 8083
inventory_service:
  endpoint: http://localhost:8082
  name: inventory-service
author_service:
  name: author-service
  endpoint: http://localhost:8081

jwt:
  secret: 123453434sdasdzxZxZxsdasdsxXzXZXzmx>zxm.zLXXCMZXCZMXLAWDLMMXCMZXCMZX123132
  issuer: thanhbinh
  audience: thanhbinh
  expired: 864000000